name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm install --frozen-lockfile
        working-directory: drizzle-orm
      - run: pnpm run build
        working-directory: drizzle-orm
      - run: pnpm run test
        working-directory: drizzle-orm
      - run: pnpm run pack
        working-directory: drizzle-orm
      - run: pnpm run publish
        working-directory: drizzle-orm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
